default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: user_status_checker_development

test:
  <<: *default
  database: user_status_checker_test